version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: gerenciador-oficina
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: oficina@123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/gerenciador-oficina/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

#  app:
#    container_name: gerenciador-oficina-core
#    build: .
#    ports:
#      - "8081:8081"
#    depends_on:
#      - postgres
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/gerenciador-oficina
#      SPRING_DATASOURCE_USERNAME: postgres
#      SPRING_DATASOURCE_PASSWORD: oficina@123

volumes:
  postgres_data:
