version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: gerenciador-oficina
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: oficina@123
    ports:
      - "5432:5432"
    volumes:
      # Corrigido: caminho oficial do volume de dados do Postgres
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  sonarqube:
    image: sonarqube:community
    container_name: sonar
    depends_on:
      - sonardb
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://sonardb:5432/sonar
      - SONAR_JDBC_USERNAME=${SONAR_JDBC_USERNAME:-sonar}
      - SONAR_JDBC_PASSWORD=${SONAR_JDBC_PASSWORD:oficina@123}
    ports:
      - "9000:9000"
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs

  sonardb:
    image: postgres:15
    container_name: sonardb
    environment:
      - POSTGRES_USER=${SONAR_JDBC_USERNAME:-sonar}
      - POSTGRES_PASSWORD=${SONAR_JDBC_PASSWORD:oficina@123}
      - POSTGRES_DB=sonar
    volumes:
      - postgresql:/var/lib/postgresql/data

volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  postgresql:
  postgres_data:
